version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: arch_admin
      POSTGRES_PASSWORD: D@h!etnBIwz*@xXU
      POSTGRES_DB: arch
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
